package provider

import (
	"crypto/ecdsa"
	"crypto/elliptic"
	"crypto/rand"
	"encoding/base64"
	"errors"
	"fmt"
	"maps"
	"strings"

	"github.com/golang-jwt/jwt/v5"
	"github.com/google/uuid"
)

type MockAuth struct {
	signingMethod jwt.SigningMethod
	key           any
	keyResponse   KeysetResponse
	customClaims  map[string]any
}

// JSONWebKey is the key format described at https://datatracker.ietf.org/doc/html/rfc7517#section-3
type JSONWebKey struct {
	KeyType              string    `json:"kty"`
	Use                  string    `json:"use"`
	KeyOps               []string  `json:"key_ops"`
	Algorithm            string    `json:"alg,omitempty"`
	KeyID                uuid.UUID `json:"kid,omitempty"`
	X509URL              string    `json:"x5u,omitempty"`
	X509Chain            []string  `json:"x5c,omitempty"`      // N.B. these should be b64 encoded strings if used
	X509ThumbprintSHA1   string    `json:"x5t,omitempty"`      // N.B. B64 uRL encoded SHA-1 thumbprint of DER encoding
	X509ThumbprintSHA256 string    `json:"x5t#S256,omitempty"` // N.B. B64 URL encoded SHA-256 thumbprint of DER encoding
	Curve                string    `json:"crv,omitempty"`      // N.B. not directly specified in the RFC but present in examples
	X                    string    `json:"x,omitempty"`        // N.B. B64 URL encoded x coordinate of ECC, not directly specified in the RFC, but present in examples
	Y                    string    `json:"y,omitempty"`        // N.B. B64 URL encoded y coordinate of ECC, not directly specified in the RFC, but present in examples
}

// KeysetResponse mocks a keyset response with a single populated JSONWebKey inside of it
// the information in the key is based on the parameters passed to the MockAuth on creation
type KeysetResponse struct {
	Keys []JSONWebKey `json:"keys"`
}

// NewMockAuth creates a new instance of a mock authenticator.
func NewMockAuth(signMethod string, keyUse string, keyOps []string) (*MockAuth, error) {
	thisMethod, privateKey, webKey, err := generateNewPrivateKey(signMethod)
	if err != nil {
		return nil, fmt.Errorf("error generating new private key: %s", err)
	}

	webKey.Use = keyUse
	webKey.KeyOps = keyOps

	keySet := KeysetResponse{Keys: []JSONWebKey{
		webKey,
	}}

	return &MockAuth{
		signingMethod: thisMethod,
		key:           privateKey,
		keyResponse:   keySet,
	}, nil
}

// SetCustomClaims will embed the provided claims into all future tokens generated by this mock authenticator.  To clear
// the custom claims simply call this method again with an empty map.
func (ma *MockAuth) SetCustomClaims(claims map[string]any) {
	ma.customClaims = claims
}

// MakeSignedToken generates a signed token with any custom claims and the provided claims added to it.  In the case of
// the provided claims colliding with custom claims, the provided claims will win.
func (ma *MockAuth) MakeSignedToken(claims map[string]any) (string, error) {
	// first apply custom claims, then apply the claims given here (if any)
	thisClaims := make(map[string]any)
	if len(ma.customClaims) > 0 {
		maps.Copy(thisClaims, ma.customClaims)
	}
	if len(claims) > 0 {
		maps.Copy(thisClaims, claims)
	}
	var jwtClaims jwt.MapClaims
	jwtClaims = thisClaims

	token := jwt.NewWithClaims(ma.signingMethod, jwtClaims)
	signedString, err := token.SignedString(ma.key)
	if err != nil {
		return "", err
	}
	return signedString, nil
}

// GetKeyResponse returns a KeysetResponse that may be marshaled and returned to the user
func (ma *MockAuth) GetKeyResponse() KeysetResponse {
	return ma.keyResponse
}

// GetPublicKey is a convenience helper to return the public key directly for tests and any future operations
// that may require knowledge of the public key.
func (ma *MockAuth) GetPublicKey() (any, error) {
	switch k := ma.key.(type) {
	case *ecdsa.PrivateKey:
		return new(k.PublicKey), nil
	default:
		return nil, errors.New("auth provider mock does not have a valid private key type, unable to get public key")
	}
}

func generateNewPrivateKey(signingMethod string) (jwt.SigningMethod, any, JSONWebKey, error) {
	var privateKey any
	newJWK := JSONWebKey{
		KeyID: uuid.New(),
	}
	var thisMethod jwt.SigningMethod

	switch strings.ToLower(signingMethod) {
	case "es256":
		k, err := ecdsa.GenerateKey(elliptic.P256(), rand.Reader)
		if err != nil {
			return nil, nil, newJWK, fmt.Errorf("error generating private key: %s", err)
		}
		keyX := base64.URLEncoding.EncodeToString(k.PublicKey.X.Bytes())
		keyY := base64.URLEncoding.EncodeToString(k.PublicKey.Y.Bytes())

		privateKey = k

		thisMethod = jwt.SigningMethodES256
		newJWK.KeyType = "EC"
		newJWK.Algorithm = "ES256"
		newJWK.Curve = k.Params().Name
		newJWK.X = keyX
		newJWK.Y = keyY
	case "es384":
		k, err := ecdsa.GenerateKey(elliptic.P384(), rand.Reader)
		if err != nil {
			return nil, nil, newJWK, fmt.Errorf("error generating private key: %s", err)
		}
		keyX := base64.URLEncoding.EncodeToString(k.PublicKey.X.Bytes())
		keyY := base64.URLEncoding.EncodeToString(k.PublicKey.Y.Bytes())

		privateKey = k

		thisMethod = jwt.SigningMethodES384
		newJWK.KeyType = "EC"
		newJWK.Algorithm = "ES384"
		newJWK.Curve = k.Params().Name
		newJWK.X = keyX
		newJWK.Y = keyY
	case "es512":
		// this is confusing because 521/512 but accurate to the RFC as far as I can tell
		// https://datatracker.ietf.org/doc/html/rfc7518#section-3.1
		k, err := ecdsa.GenerateKey(elliptic.P521(), rand.Reader)
		if err != nil {
			return nil, nil, newJWK, fmt.Errorf("error generating private key: %s", err)
		}
		keyX := base64.URLEncoding.EncodeToString(k.PublicKey.X.Bytes())
		keyY := base64.URLEncoding.EncodeToString(k.PublicKey.Y.Bytes())

		privateKey = k

		thisMethod = jwt.SigningMethodES512
		newJWK.KeyType = "EC"
		newJWK.Algorithm = "ES512"
		newJWK.Curve = k.Params().Name
		newJWK.X = keyX
		newJWK.Y = keyY
	default:
		return nil, nil, newJWK, fmt.Errorf("unsupported signing method: %s", signingMethod)
	}

	return thisMethod, privateKey, newJWK, nil
}
